### PR TITLE
Update parseQuery.js

### PR DESCRIPTION
**Pull request by psyfreak**
add handling of textIndex / search for a phrase, which could be wrongly detected as a date

### CODE REVIEW

**Review by jupe — COMMENTED** [review]
could you implement unit test as well?

**Comment by psyfreak** [comment]
yes, sorry actually it is my first pr ever on a open source repo ;)

**Comment by jupe** [comment]
hmm, what is wrong with circle 🙄

**Comment by psyfreak** [comment]
Should I help you with something here?

**Comment by jupe** [comment]
I didn’t have time to look at the circleci. I guess it just didn’t triggered because 3rd party committer. I took risk and merge 😁 functionality work fine but there was trivial lint issue witch prevent me to create release.Any change you could fix them (npm run lint)?

**Comment by psyfreak** [comment]
only to clarify I got the following eslint issues (mainly crlf linebreaks etc. and around 160 function use instead of arrow function)
 ✖ 1523 problems (1443 errors, 80 warnings)
  1438 errors and 0 warnings potentially fixable with the `--fix` option.


I am wondering if this project was linted with this version before or do I sth. wrong?

**Pull request merged**
